char *int_to_string(int n);
int string_to_int(char *s);
int len_command(char **command);
int strings_compare(char *s1, const char *s2);
void cmd_exit(char **command);
char *string_copy(char *dest, char *src);
char *read_line(int fd);
char **string_split(char *str, char seperator);
int print_env();
int str_len(char *str);
void free_command(char **command);
void init_env();
void set_env(char *name, char *value);
void cd(char *address);
char *get_env(char *check);
char *str_cat(char *dest, char *src);
char *str_ncat(char *dest, char *src, int len);
void pwd();
char *get_wd();
void *ret_correct_path(char *cmd, char **env);
int check_path(char *cmd_cpy);
void update_status(int status);
void print_status(void);
