char *int_to_string(int n);
int string_to_int(char *s);
int len_command(char **command);
int strings_compare(char *s1, const char *s2);
void cmd_exit(char **command);
char *string_copy(char *dest, char *src);
char *read_line(int fd);
char **string_split(char *str, char seperator);
int print_env(char** envp);
int str_len(char *str);
void free_command(char **command);
void init_env();
void set_env(char *name, char *value);
void cd(char *address);
